version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    logging:
      options:
        max-size: '50m'
        max-file: '3'
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:19092
      SCHEMA_REGISTRY_DEBUG: 'true'
    logging:
      options:
        max-size: '50m'
        max-file: '3'
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    logging:
      options:
        max-size: '50m'
        max-file: '3'
  mongodb:
    image: mongo:6.0.10
    command: mongod --config /etc/mongodb/mongodb.conf
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
      - ./mongodb:/etc/mongodb/
  slack:
    build:
      context: ./slack
    restart: always
    logging:
      options:
        max-size: '50m'
        max-file: '3'
  coffeechat:
    build:
      context: ./coffeechat
    ports:
      - 8080:8080
    restart: always
    logging:
      options:
        max-size: '50m'
        max-file: '3'

